# Generated by Django 4.2.5 on 2023-10-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('dni', models.CharField(max_length=12, verbose_name='DNI')),
                ('mail', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
