# Generated by Django 4.2.5 on 2023-10-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apodo',
            field=models.CharField(default='', max_length=100, verbose_name='Apodo'),
            preserve_default=False,
        ),
    ]
